export const POST_RACE_REQUEST = "POST_RACE_REQUEST";
export const POST_RACE_SUCCESS = "POST_RACE_SUCCESS";
export const POST_RACE_FAILURE = "POST_RACE_FAILURE";

export const GET_RACE_REQUEST = "GET_RACE_REQUEST";
export const GET_RACE_SUCCESS = "GET_RACE_SUCCESS";
export const GET_RACE_FAILURE = "GET_RACE_FAILURE";

export const GET_RACE_REQUEST_BY_ID = "GET_RACE_REQUEST_BY_ID";
export const GET_RACE_SUCCESS_BY_ID = "GET_RACE_SUCCESS_BY_ID";
export const GET_RACE_FAILURE_BY_ID = "GET_RACE_FAILURE_BY_ID";

export const UPDATE_RACE_REQUEST = "UPDATE_RACE_REQUEST";
export const UPDATE_RACE_SUCCESS = "UPDATE_RACE_SUCCESS";
export const UPDATE_RACE_FAILURE = "UPDATE_RACE_FAILURE";

export const DELETE_RACE_REQUEST = "DELETE_RACE_REQUEST";
export const DELETE_RACE_SUCCESS = "DELETE_RACE_SUCCESS";
export const DELETE_RACE_FAILURE = "DELETE_RACE_FAILURE";

//--------02-03-2021-----------------
export const POST_PARTICIPATE_REQUEST = "POST_PARTICIPATE_REQUEST";
export const POST_PARTICIPATE_SUCCESS = "POST_PARTICIPATE_SUCCESS";
export const POST_PARTICIPATE_FAILURE = "POST_PARTICIPATE_FAILURE";
