export const POST_TRAINING_REQUEST = "POST_TRAINING_REQUEST";
export const POST_TRAINING_SUCCESS = "POST_TRAINING_SUCCESS";
export const POST_TRAINING_FAILURE = "POST_TRAINING_FAILURE";

export const GET_TRAINING_REQUEST = "GET_TRAINING_REQUEST";
export const GET_TRAINING_SUCCESS = "GET_TRAINING_SUCCESS";
export const GET_TRAINING_FAILURE = "GET_TRAINING_FAILURE";

export const GET_TRAINING_REQUEST_BY_ID = "GET_TRAINING_REQUEST_BY_ID";
export const GET_TRAINING_SUCCESS_BY_ID = "GET_TRAINING_SUCCESS_BY_ID";
export const GET_TRAINING_FAILURE_BY_ID = "GET_TRAINING_FAILURE_BY_ID";

export const UPDATE_TRAINING_REQUEST = "UPDATE_TRAINING_REQUEST";
export const UPDATE_TRAINING_SUCCESS = "UPDATE_TRAINING_SUCCESS";
export const UPDATE_TRAINING_FAILURE = "UPDATE_TRAINING_FAILURE";

export const DELETE_TRAINING_REQUEST = "DELETE_TRAINING_REQUEST";
export const DELETE_TRAINING_SUCCESS = "DELETE_TRAINING_SUCCESS";
export const DELETE_TRAINING_FAILURE = "DELETE_TRAINING_FAILURE";
