export const POST_BREEDING_REQUEST = "POST_BREEDING_REQUEST";
export const POST_BREEDING_SUCCESS = "POST_BREEDING_SUCCESS";
export const POST_BREEDING_FAILURE = "POST_BREEDING_FAILURE";

export const GET_BREEDING_REQUEST = "GET_BREEDING_REQUEST";
export const GET_BREEDING_SUCCESS = "GET_BREEDING_SUCCESS";
export const GET_BREEDING_FAILURE = "GET_BREEDING_FAILURE";

export const GET_BREEDING_REQUEST_BY_ID = "GET_BREEDING_REQUEST_BY_ID";
export const GET_BREEDING_SUCCESS_BY_ID = "GET_BREEDING_SUCCESS_BY_ID";
export const GET_BREEDING_FAILURE_BY_ID = "GET_BREEDING_FAILURE_BY_ID";

export const UPDATE_BREEDING_REQUEST = "UPDATE_BREEDING_REQUEST";
export const UPDATE_BREEDING_SUCCESS = "UPDATE_BREEDING_SUCCESS";
export const UPDATE_BREEDING_FAILURE = "UPDATE_BREEDING_FAILURE";

export const DELETE_BREEDING_REQUEST = "DELETE_BREEDING_REQUEST";
export const DELETE_BREEDING_SUCCESS = "DELETE_BREEDING_SUCCESS";
export const DELETE_BREEDING_FAILURE = "DELETE_BREEDING_FAILURE";
